window.calendar = [
  { day: 29, empty: true},
  { day: 30, empty: true},
  { day: 1, author: null, title: null, link: null },
  { day: 2, author: null, title: null, link: null },
  { day: 3, author: null, title: null, link: null },
  { day: 4, author: null, title: null, link: null },
  { day: 5, author: null, title: null, link: null },
  { day: 6, author: null, title: null, link: null },
  { day: 7, author: null, title: null, link: null },
  { day: 8, author: null, title: null, link: null },
  { day: 9, author: null, title: null, link: null },
  { day: 10, author: null, title: null, link: null },
  { day: 11, author: null, title: null, link: null },
  { day: 12, author: null, title: null, link: null },
  { day: 13, author: null, title: null, link: null },
  { day: 14, author: null, title: null, link: null },
  { day: 15, author: null, title: null, link: null },
  { day: 16, author: null, title: null, link: null },
  { day: 17, author: null, title: null, link: null },
  { day: 18, author: null, title: null, link: null },
  { day: 19, author: null, title: null, link: null },
  { day: 20, author: null, title: null, link: null },
  { day: 21, author: null, title: null, link: null },
  { day: 22, author: null, title: null, link: null },
  { day: 23, author: null, title: null, link: null },
  { day: 24, author: null, title: null, link: null },
  { day: 25, title: 'X-Mas', force: true },
  { day: 26, empty: true},
];