window.calendar = [
  { day: 29, empty: true},
  { day: 30, empty: true},
  { day: 1, author: null, title: null, link: null },
  { day: 2, author: null, title: null, link: null },
  { day: 3, author: null, title: null, link: null },
  { day: 4, author: null, title: null, link: null },
  { day: 5, author: null, title: null, link: null },
  { day: 6, author: null, title: null, link: null },
  { day: 7, author: null, title: null, link: null },
  { day: 8, author: null, title: null, link: null },
  { day: 9, author: null, title: null, link: null },
  { day: 10, author: null, title: null, link: null },
  { day: 11, author: null, title: null, link: null },
  { day: 12, author: '@lemonade', title: '바지벗고 일하면 안되나요', link: 'http://bitterlemonism.tumblr.com/' },
  { day: 13, author: null, title: null, link: null },
  { day: 14, author: '@taromati', title: '지적 대화를 위한 넓고 얕은 지식', link: 'http://taromati.kr/blog' },
  { day: 15, author: null, title: null, link: null },
  { day: 16, author: null, title: null, link: null },
  { day: 17, author: null, title: null, link: null },
  { day: 18, author: null, title: null, link: null },
  { day: 19, author: null, title: null, link: null },
  { day: 20, author: null, title: null, link: null },
  { day: 21, author: null, title: null, link: null },
  { day: 22, author: '@raccoony', title: '멀티미디어 : 바그너에서 가상현실까지', link: 'https://raccoonyy.github.io/' },
  { day: 23, author: '@arzhna', title: '(미정)', link: 'http://note.arzhna.net' },
  { day: 24, author: '@nipol', title: '이바나', link: 'https://medium.com/@NipolNIpol' },
  { day: 25, title: 'X-Mas', force: true },
  { day: 26, empty: true},
];