window.calendar = [
  { day: 29, empty: true},
  { day: 30, empty: true},
  { day: 1, author: '@minieetea', title: '미정', link: 'http://minieetea.com' },
  { day: 2, author: '@sjyun', title: '[한빛미디어] 팟캐스트 나는 프로그래머다: 뉴욕, 서울, 도쿄 개발자의 촌철살인 IT 이야기', link: 'http://devluna.blogspot.kr/search?max-results=1' },
  { day: 3, author: '@haruair', title: 'Thinking, Fast and Slow', link: 'http://haruair.com' },
  { day: 4, author: null, title: null, link: null },
  { day: 5, author: null, title: null, link: null },
  { day: 6, author: '@devgrapher', title: '철학적 시 읽기의 즐거움', link: 'http://devgrapher.com' },
  { day: 7, author: '@shoo7830', title: '문구의 모험', link: 'http://webholic.net' },
  { day: 8, author: '@chiyodad', title: '다시 시작하는 프로그래밍 : 자바스크립트로 배우는 웹 프로그래밍 A to Z', link: 'https://medium.com/@chiyodad' },
  { day: 9, author: null, title: null, link: null },
  { day: 10, author: '@haegyung', title: '블루오션 전략,다윗과 골리앗', link: 'http://haegyung.com' },
  { day: 11, author: null, title: null, link: null },
  { day: 12, author: '@lemonade', title: '바지벗고 일하면 안되나요', link: 'http://bitterlemonism.tumblr.com/' },
  { day: 13, author: null, title: null, link: null },
  { day: 14, author: '@taromati', title: '지적 대화를 위한 넓고 얕은 지식', link: 'http://taromati.kr/blog' },
  { day: 15, author: null, title: null, link: null },
  { day: 16, author: null, title: null, link: null },
  { day: 17, author: '@ggubi', title: '컴퓨터 아나토미', link: 'http://blog.naver.com/hst393' },
  { day: 18, author: null, title: null, link: null },
  { day: 19, author: null, title: null, link: null },
  { day: 20, author: null, title: null, link: null },
  { day: 21, author: null, title: null, link: null },
  { day: 22, author: '@raccoony', title: '멀티미디어 : 바그너에서 가상현실까지', link: 'https://raccoonyy.github.io/' },
  { day: 23, author: '@arzhna', title: '(미정)', link: 'http://note.arzhna.net' },
  { day: 24, author: '@nipol', title: '이바나', link: 'https://medium.com/@NipolNIpol' },
  { day: 25, title: 'X-Mas', force: true },
  { day: 26, empty: true},
];
